apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DATABASE_URI: "mysql+pymysql://admin:Password1234!@flask-db.cbf9oalhjjnm.eu-west-1.rds.amazonaws.com:3306/flaskdb"

