apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp-pod
  name: flask-app
spec:
  containers:
  - name: myapp-container
    image: aatkinson42/flask-app:latest
    env:
    - name: DATABASE_URI
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: DATABASE_URI
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-cluster
spec:
  selector:
    app: myapp-pod
  ports:
  - protocol: TCP
    port: 5000
  type: ClusterIP
